<DashboardPage>:
    FloatLayout:

        Label:
            pos_hint: {"right": 0.85 , "top": 0.95}
            size_hint: 0.7, 0.2
            text:Dashboard"

        # Botão voltar
        FloatLayout:
          LabelButton:
                pos_hint: {"right": 0.2, "top": 0.9}
                size_hint: 0.20, 0.8
                source: "icones/voltar.png"
                on_release: app.mudar_tela("inicialpage")